### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by JustKatze** [Buam/nolimits2-csv-exporter#1]
Hey if i want to open the NLCSV.jar
I get this erro here
![image](https://user-images.githubusercontent.com/46849183/88834959-e0064280-d1d4-11ea-894e-3f208807c15f.png)

I have installed Java
Version:  Version 8 Update 261 (Build 1.8.0_261-b12)

**Comment by Buam** [comment]
Hey!
Try downloading the older version: [Version 1.0](https://github.com/Buam/nolimits2-csv-exporter/releases/download/1.0/nl2-csv-exporter.jar)
If that doesn't work, try installing a newer Java version

**Comment by JustKatze** [comment]
Yeah this works Thx

**Comment by ajackson2** [comment]
I had same problem
