### ISSUE TITLE
Problem with version 1.1

### ISSUE THREAD

**Issue by Maxoulin** [Buam/nolimits2-csv-exporter#2]
Hey! I would need to use version 1.1 however despite all my manipulations with Java (consisting in retrying later versions ect ...).

The program still does not work, do you have a reason for this problem? Because its addition compared to the previous one is essential.

Sincerely, awaiting your response.

**Comment by crlxtt** [comment]
Hey! I would like to report an issue with the latest version of this. No matter what versions of Java I install, I can not seem to get the Java exe open. This is something I am really needing at the moment and it would be great if you could get back to me with a response. Thank you.

**Comment by Buam** [comment]
It works with Java 12.0.1. I'll push a new release that works with Java 16 as well.
